# Generated by Django 5.1.4 on 2025-01-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('magic_element', models.CharField(blank=True, choices=[('EAU', 'Eau'), ('FEU', 'Feu'), ('AIR', 'Air'), ('TERRE', 'Terre')], max_length=10, null=True)),
                ('type', models.CharField(choices=[('ARME', 'Arme'), ('ARMURE', 'Armure')], max_length=15)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('battle_score', models.IntegerField(blank=True, default=0, null=True)),
                ('coins', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('magic_element', models.CharField(choices=[('EAU', 'Eau'), ('FEU', 'Feu'), ('AIR', 'Air'), ('TERRE', 'Terre')], max_length=10)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, null=True, to='app_game_logic.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slimes', to='app_game_logic.player')),
            ],
        ),
    ]
