# Generated by Django 5.1.4 on 2025-01-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0003_item_agility_slime_agility_alter_player_battle_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='items',
            field=models.ManyToManyField(blank=True, to='app_game_logic.item'),
        ),
    ]
