# Generated by Django 5.1.4 on 2025-01-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0004_player_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('ACTIVE', 'Active'), ('PASSIVE', 'Passive')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='slime',
            name='skills',
            field=models.ManyToManyField(blank=True, to='app_game_logic.skill'),
        ),
    ]
