# Generated by Django 5.1.4 on 2025-01-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0006_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='magic_element',
            field=models.CharField(blank=True, choices=[('EAU', 'Eau'), ('FEU', 'Feu'), ('AIR', 'Air'), ('TERRE', 'Terre'), ('NEUTRE', 'Neutre')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='slime',
            name='magic_element',
            field=models.CharField(choices=[('EAU', 'Eau'), ('FEU', 'Feu'), ('AIR', 'Air'), ('TERRE', 'Terre'), ('NEUTRE', 'Neutre')], default='NEUTRE', max_length=10),
        ),
    ]
