# Generated by Django 5.1.4 on 2025-01-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0007_alter_item_magic_element_alter_slime_magic_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='item',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='item',
            name='magic_element',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='skills',
            field=models.ManyToManyField(blank=True, to='app_game_logic.skill'),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_game_logic.item')),
                ('defense', models.IntegerField(default=0)),
            ],
            bases=('app_game_logic.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_game_logic.item')),
                ('attack', models.IntegerField(default=0)),
                ('magic_element', models.CharField(blank=True, choices=[('EAU', 'Eau'), ('FEU', 'Feu'), ('AIR', 'Air'), ('TERRE', 'Terre'), ('NEUTRE', 'Neutre')], max_length=10, null=True)),
            ],
            bases=('app_game_logic.item',),
        ),
    ]
