# Generated by Django 5.1.4 on 2025-01-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0008_remove_item_defense_remove_item_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slime',
            name='magic_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slime',
            name='magic_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SkillEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('POISON', 'Poison'), ('STUN', 'Stun'), ('BURN', 'Burn'), ('FREEZE', 'Freeze'), ('ELECTROCUTE', 'Electrocute'), ('HEAL', 'Heal'), ('BUFF', 'Buff'), ('DEBUFF', 'Debuff')], max_length=15)),
                ('power', models.FloatField(help_text='Strength of the effect, e.g., poison damage per turn.')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in turns for the effect.', null=True)),
                ('chance', models.FloatField(default=1.0, help_text='Chance (0.0 to 1.0) for the effect to apply.')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='app_game_logic.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SlimeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_game_logic.item')),
                ('slime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_game_logic.slime')),
            ],
            options={
                'unique_together': {('slime', 'item')},
            },
        ),
    ]
