# Generated by Django 5.1.4 on 2025-01-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0009_slime_magic_attack_slime_magic_defense_skilleffect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slime',
            name='items',
        ),
    ]
