# Generated by Django 5.1.4 on 2025-01-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0010_remove_slime_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='slime',
            name='items',
            field=models.ManyToManyField(through='app_game_logic.SlimeItem', to='app_game_logic.item'),
        ),
    ]
