# Generated by Django 5.1.4 on 2025-01-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0012_armor_magic_defense_weapon_magic_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='slime',
            name='hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='slime',
            name='max_hp',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='slime',
            name='magic_element',
            field=models.CharField(choices=[('FLAMME', 'Flamme'), ('VAGUE', 'Vague'), ('OMBRE', 'Ombre'), ('LUMIERE', 'Lumière'), ('METAUX', 'Métaux'), ('ETHERE', 'Éthéré'), ('TEMPESTE', 'Tempête'), ('ECHO', 'Echo'), ('FUSION', 'Fusion')], default='NEUTRE', max_length=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='magic_element',
            field=models.CharField(blank=True, choices=[('FLAMME', 'Flamme'), ('VAGUE', 'Vague'), ('OMBRE', 'Ombre'), ('LUMIERE', 'Lumière'), ('METAUX', 'Métaux'), ('ETHERE', 'Éthéré'), ('TEMPESTE', 'Tempête'), ('ECHO', 'Echo'), ('FUSION', 'Fusion')], max_length=10, null=True),
        ),
    ]
