# Generated by Django 5.1.4 on 2025-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0014_slime_in_active_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='slime',
            name='is_fighter',
            field=models.BooleanField(default=False),
        ),
    ]
