# Generated by Django 5.1.4 on 2025-01-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0015_slime_is_fighter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
