# Generated by Django 5.1.4 on 2025-01-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0016_remove_weapon_item_ptr_delete_armor_delete_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='magic_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='magic_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='magic_element',
            field=models.CharField(choices=[('FLAMME', 'Flamme'), ('VAGUE', 'Vague'), ('OMBRE', 'Ombre'), ('LUMIERE', 'Lumière'), ('METAUX', 'Métaux'), ('ETHERE', 'Éthéré'), ('TEMPESTE', 'Tempête'), ('ECHO', 'Echo'), ('FUSION', 'Fusion')], default='NEUTRE', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('ARME', 'Arme'), ('ARMURE', 'Armure')], max_length=50, null=True),
        ),
    ]
