# Generated by Django 5.1.4 on 2025-01-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0018_remove_slime_items_delete_slimeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='items',
        ),
    ]
