# Generated by Django 5.1.4 on 2025-01-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0019_remove_player_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='slime',
            name='items',
            field=models.ManyToManyField(blank=True, to='app_game_logic.item'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_game_logic.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_items', to='app_game_logic.player')),
            ],
            options={
                'unique_together': {('player', 'item')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='items',
            field=models.ManyToManyField(through='app_game_logic.Inventory', to='app_game_logic.item'),
        ),
    ]
