# Generated by Django 5.1.4 on 2025-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0020_slime_items_inventory_player_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='power',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(default='Descritpion'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Skill Undifined', max_length=120),
        ),
    ]
