# Generated by Django 5.1.4 on 2025-01-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0021_skill_power_alter_skill_description_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilleffect',
            name='skill',
        ),
    ]
