# Generated by Django 5.1.4 on 2025-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0022_remove_skilleffect_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='effects',
            field=models.ManyToManyField(related_name='skills', to='app_game_logic.skilleffect'),
        ),
    ]
