# Generated by Django 5.1.4 on 2025-01-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0023_skill_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='slime',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
