# Generated by Django 5.1.4 on 2025-02-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_logic', '0025_ennemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='magic_element',
            field=models.CharField(choices=[('FLAMME', 'Flamme'), ('VAGUE', 'Vague'), ('OMBRE', 'Ombre'), ('LUMIERE', 'Lumière'), ('METAUX', 'Métaux'), ('ETHERE', 'Éthéré'), ('TEMPESTE', 'Tempête'), ('ECHO', 'Echo'), ('FUSION', 'Fusion')], default='NEUTRE', max_length=10),
        ),
    ]
